-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 00:12:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 ;
USE `academia` ;

-- -----------------------------------------------------
-- Table `academia`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`alunos` (
  `Matricula` INT(10) NOT NULL AUTO_INCREMENT,
  `Telefone` VARCHAR(50) NOT NULL,
  `Endereco` TEXT NOT NULL,
  `Bairro` VARCHAR(50) NOT NULL,
  `Data_Matricula` DATETIME NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`diasemana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`diasemana` (
  `iddiasemana` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddiasemana`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`instrutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`instrutores` (
  `Id` INT(10) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(80) NOT NULL,
  `Telefone` VARCHAR(20) NOT NULL,
  `Endereco` VARCHAR(100) NOT NULL,
  `Bairro` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`modalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`modalidades` (
  `Id` INT(10) NOT NULL AUTO_INCREMENT,
  `Descricao` TEXT NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`turmas` (
  `Id` INT(10) NOT NULL AUTO_INCREMENT,
  `Duracao` INT(3) NOT NULL,
  `Hora_Inicio` TIME NOT NULL,
  `atividades_Id` INT(10) NOT NULL,
  `diasemana_iddiasemana` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_turmas_modalidades1_idx` (`atividades_Id` ASC),
  INDEX `fk_turmas_diasemana1_idx` (`diasemana_iddiasemana` ASC),
  CONSTRAINT `fk_turmas_modalidades1`
    FOREIGN KEY (`atividades_Id`)
    REFERENCES `academia`.`modalidades` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_diasemana1`
    FOREIGN KEY (`diasemana_iddiasemana`)
    REFERENCES `academia`.`diasemana` (`iddiasemana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `academia`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aulas` (
  `instrutores_Id` INT(10) NOT NULL,
  `alunos_Matricula` INT(10) NOT NULL,
  `turmas_Id` INT(10) NOT NULL,
  PRIMARY KEY (`instrutores_Id`, `alunos_Matricula`, `turmas_Id`),
  INDEX `fk_instrutores_has_alunos_alunos1_idx` (`alunos_Matricula` ASC),
  INDEX `fk_instrutores_has_alunos_instrutores1_idx` (`instrutores_Id` ASC),
  INDEX `fk_aulas_turmas1_idx` (`turmas_Id` ASC),
  CONSTRAINT `fk_instrutores_has_alunos_instrutores1`
    FOREIGN KEY (`instrutores_Id`)
    REFERENCES `academia`.`instrutores` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instrutores_has_alunos_alunos1`
    FOREIGN KEY (`alunos_Matricula`)
    REFERENCES `academia`.`alunos` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aulas_turmas1`
    FOREIGN KEY (`turmas_Id`)
    REFERENCES `academia`.`turmas` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
